# ------------------------------------------------------------------------------------------------ #
[versions]
## --- Plugins and more general stuff --- ##
jacoco = "0.8.14"
detekt = "1.23.8"

## --- Build Config and SDK --- ##
build-version-name = "1.0.0"
build-version-code = "1"
build-sdk-min-toolkit = "28"
build-sdk-min-sample = "28"
build-sdk-compile = "36"
build-sdk-target = "36"
build-tools = "36.1.0"

## JetBrains
jetbrains-kotlin = "2.3.10"
jetbrains-compose = "1.10.0"
jetbrains-lifecycle = "2.10.0-alpha08"
jetbrains-coroutines = "1.10.2"
jetbrains-serialization = "1.10.0"
jetbrains-dokka = "2.1.0"
jetbrains-datetime = "0.7.1"

## AndroidX
androidx-plugin = "8.13.2"
androidx-appcompat = "1.7.1"
androidx-annotation = "1.9.1"
androidx-constraint = "2.2.1"
androidx-recyclerview = "1.4.0"
androidx-lifecycle = "2.10.0"
androidx-window = "1.5.1"
androidx-security = "1.1.0"
androidx-startup = "1.2.0"
androidx-datastore = "1.2.0"
androidx-test-core = "2.2.0"
androidx-test-junit = "1.3.0"
androidx-test-espresso = "3.7.0"

## AndroidX Compose
androidx-compose-core = "1.10.2"
androidx-compose-activity = "1.12.3"

## SquareUp
square-retrofit = "3.0.0"
square-okhttp = "5.3.2"

## Google
google-material = "1.13.0"
google-ksp = "2.3.5"

## Arch Toolkit
arch-lumber = "1.0.1"

## Dependency Injection
di-koin = "4.1.1"

## Tools
mockk = "1.14.9"
junit = "4.13.2"
robolectric = "4.16.1"
ktlint = "11.6.1"
dexcount = "4.0.0"
vanniktech-publish = "0.36.0"
ktorfit = "2.7.2"
ktor = "3.4.0"
coil = "3.3.0"
haze = "1.7.1"

# ------------------------------------------------------------------------------------------------ #
[libraries]
## JetBrains
jetbrains-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "jetbrains-kotlin" }
jetbrains-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "jetbrains-kotlin" }
jetbrains-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "jetbrains-serialization" }
jetbrains-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "jetbrains-coroutines" }
jetbrains-coroutines-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "jetbrains-coroutines" }
jetbrains-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "jetbrains-coroutines" }
jetbrains-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "jetbrains-coroutines" }
jetbrains-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "jetbrains-dokka" }
jetbrains-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "jetbrains-kotlin" }
jetbrains-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "jetbrains-datetime" }
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "jetbrains-kotlin" }

## Androidx
androidx-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidx-plugin" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraint = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraint" }
androidx-recycler = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }
androidx-security = { module = "androidx.security:security-crypto-ktx", version.ref = "androidx-security" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
androidx-datastore-core = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-test-core = { module = "androidx.arch.core:core-testing", version.ref = "androidx-test-core" }
androidx-test-window = { module = "androidx.window:window-testing", version.ref = "androidx-window" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-junit" }
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-test-espresso" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }

## Androidx / Jetbrains Compose
androidx-compose-material3-window = { module = "org.jetbrains.compose.material3:material3-window-size-class", version = "1.10.0-alpha05" }
androidx-compose-material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version = "1.3.0-alpha04" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-compose-activity" }
androidx-compose-lifecycle = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "jetbrains-lifecycle" }
androidx-compose-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose-core" }

## SquareUp
square-retrofit-main = { module = "com.squareup.retrofit2:retrofit", version.ref = "square-retrofit" }

## Arch Toolkit
arch-lumber = { module = "io.github.matheus-corregiari:arch-lumber", version.ref = "arch-lumber" }

## Google
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }

## Dependency Injection
di-koin-core = { module = "io.insert-koin:koin-core", version.ref = "di-koin" }
di-koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "di-koin" }
di-koin-composeViewModel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "di-koin" }
di-koin-android = { module = "io.insert-koin:koin-android", version.ref = "di-koin" }

## Tools
mockk-test-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-test-agent = { module = "io.mockk:mockk", version.ref = "mockk" }
junit-test = { module = "junit:junit", version.ref = "junit" }
robolectric-test = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
ktlint = { module = "org.jlleitschuh.gradle.ktlint-idea:org.jlleitschuh.gradle.ktlint-idea.gradle.plugin", version.ref = "ktlint" }
vanniktech-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-publish" }
ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
coil-core = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
haze-core = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }

# ------------------------------------------------------------------------------------------------ #
## Comment this when you start to update some libraries
x-normalize-x001 = { module = "androidx.activity:activity", version.ref = "androidx-compose-activity" }
x-normalize-x002 = { module = "androidx.annotation:annotation-experimental", version = "1.5.1" }
x-normalize-x003 = { module = "androidx.arch.core:core-common", version = "2.2.0" }
x-normalize-x004 = { module = "androidx.arch.core:core-runtime", version = "2.2.0" }
x-normalize-x005 = { module = "androidx.collection:collection", version = "1.5.0" }
x-normalize-x006 = { module = "androidx.core:core", version = "1.17.0" }
x-normalize-x007 = { module = "androidx.core:core-ktx", version = "1.17.0" }
x-normalize-x008 = { module = "androidx.customview:customview", version = "1.2.0" }
x-normalize-x009 = { module = "androidx.drawerlayout:drawerlayout", version = "1.2.0" }
x-normalize-x010 = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
x-normalize-x011 = { module = "androidx.viewpager2:viewpager2", version = "1.1.0" }
x-normalize-x012 = { module = "androidx.test:monitor", version = "1.8.0" }
x-normalize-x013 = { module = "androidx.test:runner", version = "1.7.0" }
x-normalize-x014 = { module = "com.google.auto.value:auto-value-annotations", version = "1.11.1" }
x-normalize-x015 = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
x-normalize-x016 = { module = "com.squareup:javawritter", version = "2.5.0" }
x-normalize-x017 = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "jetbrains-kotlin" }
x-normalize-x018 = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm", version.ref = "jetbrains-serialization" }
x-normalize-x019 = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core-jvm", version.ref = "jetbrains-serialization" }
x-normalize-x020 = { module = "org.jetbrains:annotations", version = "26.0.2-1" }
x-normalize-x021 = { module = "com.squareup.okhttp3:okhttp", version.ref = "square-okhttp" }

# ------------------------------------------------------------------------------------------------ #
[plugins]
## Android
android-application = { id = "com.android.application", version.ref = "androidx-plugin" }
android-library = { id = "com.android.library", version.ref = "androidx-plugin" }

## Android
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }

## JetBrains
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrains-kotlin" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "jetbrains-dokka" }
jetbrains-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrains-kotlin" }
jetbrains-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jetbrains-kotlin" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "jetbrains-kotlin" }
jetbrains-compose-kotlin = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }

## Tools to make my life easier
dexcount = { id = "com.getkeepsafe.dexcount", version.ref = "dexcount" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint-idea", version.ref = "ktlint" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-publish" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }

# ------------------------------------------------------------------------------------------------ #
[bundles]

## Nothing Here Yet!
